<?php
/**
 * class-rb-prestation.php
 * 
 * Project: wp-production2
 * User:    Félix Dion Robidoux
 * Date:    17/02/2015
 * Time:    9:35 AM
 */

class RB_Prestation extends RB_Section
{
	/** @const  String Le nom de la slug par défaut. */
	const SLUG_DEFAULT = 'rb-prestation-slug';

	/**
	 * Constructeur. Fais pas mal de choses!
	 *
	 * > NOTE DE FÉLIX: <br />
	 * > C't'une pas pire de bonne idée d'inspecter le code pour cte fonction-là!
	 *
	 * @access public
	 * @param null|RB_Loader $loader Le loader qui va être appelé pour les hooks.
	 */
	public function __construct( RB_Loader $loader )
	{
		parent::__construct( $loader ); // TODO: Change the autogenerated stub
	}

	/**
	 * Charge les dépendances du programme.
	 *
	 * Lorsqu'on crée une nouvelle
	 *
	 * @access public
	 * @see    RB::load_all_dependencies
	 */
	public function load_dependencies()
	{

	}

	/**
	 * Définit tous les hooks de la fonction
	 *
	 * @param \RB_Loader $loader
	 */
	protected function define_hooks( RB_Loader $loader )
	{
		// TODO: Implement define_hooks() method.
	}

	/**
	 * Définit les hooks du panneau d'administration.
	 *
	 * @access  protected
	 * @see     RB::define_all_admin_hooks
	 *
	 * @param   \RB_Loader $loader Un pointeur vers le loader.
	 */
	protected function define_admin_hooks(RB_Loader $loader)
	{
		// Créer l'objet qui gère le panneau d'administration.
		$admin = new RB_Spectacle_Admin( $this->get_version() );

		// Ajouter les actions du panneau d'admin à la queue d'action du composant loader.
		$loader->queue_action( 'admin_enqueue_scripts', $admin, 'enqueue_styles' );
	}
}