<?php

/**
 * Class RB_Prestation
 *
 * Les prestations.
 */
class RB_Prestation extends RB_Section
{
	/** @const  String Le nom de la slug par défaut. */
	const SLUG_DEFAULT = 'rb-prestation-slug';

	public $admin;

	/**
	 * Constructeur. Fais pas mal de choses!
	 *
	 * > NOTE DE FÉLIX: <br />
	 * > C't'une pas pire de bonne idée d'inspecter le code pour cte fonction-là!
	 *
	 * @access public
	 * @param null|RB_Loader $loader Le loader qui va être appelé pour les hooks.
	 */
	public function __construct( RB_Loader $loader )
	{
		parent::__construct( $loader ); // TODO: Change the autogenerated stub
	}

	/**
	 * Charge les dépendances du programme.
	 *
	 * Lorsqu'on crée une nouvelle
	 *
	 * @access public
	 * @see    RB::load_all_dependencies
	 */
	public function load_dependencies()
	{
		if ( $this->is_admin ) {
			/** @noinspection PhpIncludeInspection */
			require_once plugin_dir_path( dirname( __FILE__ ) ) . 'admin/class-rb-prestation-admin.php';
		}
	}

	/**
	 * Définit tous les hooks de la fonction
	 *
	 * @param \RB_Loader $loader
	 */
	protected function define_hooks( RB_Loader $loader )
	{
		// Création du Custom post-type
		$loader->queue_action( 'init', $this, 'create_post_type' );

		// Utiliser les hooks du panneau d'administration.
		if ($this->is_admin) {
			$this->define_admin_hooks( $loader );
		}
	}

	/**
	 * Définit les hooks du panneau d'administration.
	 *
	 * @access  protected
	 * @see     RB::define_all_admin_hooks
	 *
	 * @param   \RB_Loader $loader Un pointeur vers le loader.
	 */
	protected function define_admin_hooks(RB_Loader $loader)
	{
		$args = array(
			'version' => $this->get_version(),
			'' => ''
		);
		
		// Créer l'objet qui gère le panneau d'administration.
		$admin = new RB_Prestation_Admin( $args );

		// Ajouter les actions du panneau d'admin à la queue d'action du composant loader.
		$loader->queue_action( 'admin_enqueue_scripts', $admin, 'enqueue_styles' );

		$loader->queue_action( 'admin_init', $admin, 'add_info_meta_box' );

		$loader->queue_action( 'save_post', $admin, 'save_custom_post', 10, 2 );

		$loader->queue_filter( 'manage_prestation_posts_columns', $admin, 'set_post_list_columns', 10, 1 );

		$loader->queue_action( 'manage_prestation_posts_custom_column', $admin, 'display_custom_columns_data', 10, 2 );
		
		$loader->queue_filter( 'manage_edit-prestation_sortable_columns', $admin, 'sort_custom_columns' );
		
		$loader->queue_filter( 'request', $admin, 'orderby_custom_columns' );

		//		$loader->queue_action( 'admin_init', $admin, 'add_artiste_meta_box' );
	}

	/* ################################ */
	/* DÉBUT DES FONCTIONS DE CALLBACKS */
	/* ################################ */

	public function create_post_type()
	{
		// Déclarer les labels du post-type.
		$labels = array(
			'name'                => _x( 'Prestations', 'Post Type General Name', '/langage' ),
			'singular_name'       => _x( 'Prestation', 'Post Type Singular Name', '/langage' ),
			'menu_name'           => __( 'Prestation', '/langage' ),
			'parent_item_colon'   => __( 'Faisant parti du Spectacle: ', '/langage' ),
			'all_items'           => __( 'Toutes les Prestations', '/langage' ),
			'view_item'           => __( 'Voir les infos de la Prestation', '/langage' ),
			'add_new_item'        => __( 'Ajouter une Prestation', '/langage' ),
			'add_new'             => __( 'Ajouter', '/langage' ),
			'edit_item'           => __( 'Éditer les infos de la Prestation', '/langage' ),
			'update_item'         => __( 'Mettre à jour les infos de la Prestation', '/langage' ),
			'search_items'        => __( 'Chercher une Prestation', '/langage' ),
			'not_found'           => __( 'Non-trouvé', '/langage' ),
			'not_found_in_trash'  => __( 'Non-trouvé dans la corbeille', '/langage' ),
		);

		// Déclarer les arguments du rewrite pour le post-type.
		$rewrite = array(
			'slug'                => 'prestation',
			'with_front'          => true,
			'pages'               => true,
			'feeds'               => true,
		);

		// Déclarer les arguments principaux du post-type.
		$args = array(
			'label'               => __( 'prestation', '/langage' ),
			'description'         => __( 'Une prestation.', '/langage' ),
			'labels'              => $labels,
			'supports'            => array( '' ),
			'taxonomies'          => array( '' ),
			'hierarchical'        => false,
			'public'              => true,
			'show_ui'             => true,
			'show_in_menu'        => true,
			'show_in_nav_menus'   => true,
			'show_in_admin_bar'   => true,
			'menu_position'       => 25, // Sous les commentaires.
			'menu_icon'           => 'dashicons-tickets-alt', // Icône bin sympa
			'can_export'          => true, // Pour faire des backups.
			'has_archive'         => true, // Eh, why not?
			'exclude_from_search' => true, // On veut être capable de les rechercher.
			'publicly_queryable'  => true,
			'rewrite'             => $rewrite,
			'capability_type'     => 'post', // C'est pas vraiment un post.
		);

		// Enregistre le post-type à l'aide de la liste d'arguments.
		register_post_type( 'prestation', $args );
	}
}
